# Generated by Django 3.2 on 2021-08-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_auto_20210818_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='airbnb',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='amazon',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='blog',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='book',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='cloud',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='codepen',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='database',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='email',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='google_drive',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='google_play',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='hackerRank',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='qr_code',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='quora',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='reddit',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='slideshare',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='snapchat',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='telegram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitch',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
