# Generated by Django 3.2 on 2021-08-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_alter_link_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='database',
            new_name='discord',
        ),
    ]
