# Generated by Django 3.2 on 2021-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='whatsapp',
            field=models.URLField(blank=True, default=''),
        ),
    ]
