# Generated by Django 3.2 on 2021-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_link_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='google_forms',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='spotify',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='vimeo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
